[package]
name = "tower-grpc-build"
version = "0.1.0"
edition = "2018"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"

[dependencies]
codegen = "0.1.1"
prost-build = "0.5"
heck = "0.3"

[features]
tower-hyper = []
